# Adapted from official Passenger/nginx documentation:
# http://www.modrails.com/documentation/Users%20guide%20Nginx.html


# NOTE: Using the Phusion Passenger repo for nginx.

#- name: Add the nginx PPA
#  command: add-apt-repository -y ppa:nginx/stable creates=/etc/apt/source.list.d/nginx-stable-precise.list creates=/etc/apt/sources.list.d/nginx-stable-precise.list

#- name: Install nginx
#  apt: pkg=nginx state=latest update_cache=true


# Can't seem to use keyserver= apt_key feature here
# See https://groups.google.com/forum/#!topic/ansible-project/8SEZWEQGTsg
- name: Add Phusion Passenger repo key
  apt_key: url=http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x561F9B9CAC40B2F7 state=present

- name: Install packages to enable apt over HTTPS
  action: apt pkg={{item}} state=installed update_cache=true
  with_items:
    - apt-transport-https
    - ca-certificates

- name: Add Phusion Passenger repo
  apt_repository: repo='deb https://oss-binaries.phusionpassenger.com/apt/passenger precise main'

- name: Install nginx-extras and passenger
  action: apt pkg={{item}} state=installed update_cache=true
  with_items:
    # note: Passenger repo has it's own nginx-extras package.
    - nginx-extras
    - passenger

- name: Remove the default nginx app's config
  file: path=/etc/nginx/sites-available/default state=absent

- name: Remove the default nginx app's symlink if it exists
  file: path=/etc/nginx/sites-enabled/default state=absent

# Note: Will do this in Capistrano, for now.

#- name: Configure nginx for the app
#  template: src={{ app_name }}.j2 dest=/etc/nginx/sites-available/{{ app_name }} group={{ deploy }} owner={{ deploy }} force=yes

#- name: Enable the app
#  file: src=/etc/nginx/sites-available/{{ app_name }} dest=/etc/nginx/sites-enabled/{{ app_name }} state=link owner={{ deploy }} group={{ deploy }}

- name: Copy nginx.conf
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf

- name: Start nginx
  service: name=nginx state=started